### PR TITLE
Fix #14 Tests fail with spring-web:5.2.3 and hateoas:1.0.3

### LINKED ISSUE #14: Tests fail with spring-web:5.2.3 and hateoas:1.0.3
I was having a problem when upgrading one of my apps to Spring Boot 2.2 (latest) and I've traced it down to the latest versions of one or both of these:

- org.springframework:spring-web:5.2.3.RELEASE
- org.springframework.hateoas:spring-hateoas:1.0.3.RELEASE

To verify I cloned ununbium/hateoasutils and upgraded the pom.xml to point at these specific versions. When I run the tests, they fail in the same way.

The full [output of the run is attached](https://github.com/ununbium/HateoasUtils/files/4104087/output.txt) but the main issue is:

`org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class java.lang.Class: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class java.lang.Class`

which is happening `at rocks.spiffy.spring.hateoas.utils.uri.resolver.ControllerBaseUriResolverFactory.<init>(ControllerBaseUriResolverFactory.java:34)`

If I downgrade to Spring Boot 2.2.2.RELEASE it works. That takes these two libs to:

- org.springframework:spring-web:5.2.2.RELEASE
- org.springframework.hateoas:spring-hateoas:1.0.2.RELEASE

So it was something introduced in the latest versions.

### PR DESCRIPTION
**Pull request by reda-alaoui**
This change is not backward compatible with Spring HATEOAS 1.0.2 and earlier.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello? :)

**Comment by ununbium** [comment]
Hey Réda, Firstly thanks again for contributing. My apologies for the delay. This feels like a major version since we'll be breaking it for people not up to date on dependencies. I'm thinking this goes into 3.0.0 and we release straight away, since there are no other changes queued. Are you happy with that approach?

**Comment by reda-alaoui** [comment]
Hey,
Yeah looks good

**Comment by reda-alaoui** [comment]
Do you expect me to bump the version in this PR?

**Comment by ununbium** [comment]
No thanks, I'll sort that as part of the release

**Pull request merged**
